# Generated by Django 4.2.1 on 2023-05-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schudeler', '0004_citas'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
