# Generated by Django 4.2.1 on 2023-05-31 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schudeler', '0005_citas_activa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='cita_id',
        ),
    ]
